server:
  port: 8085
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: VIEW_SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/view/**